name: Deployment 
on:
  push:
    branches:
      - master
      - beta

jobs:
  deploy:
    name: Deploy to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
      - name: Install dependencies
        run: npm ci 
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }} # personal access token with push access to the repo
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # npm token to deploy to npm 
        run: npx semantic-release